---
title: "vtamR Developer notes"
auhor: Emese Meglecz
date: "2024-06-24"
output:
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```


```{r}

install.packages(c("devtools", "roxygen2", "usethis", "testthat"))
usethis::create_package("path/to/your/packageName")

devtools::document() # generate doc

#For developer
devtools::load_all()   # Load package without installing
devtools::check()      # Run checks
## OR rcmdcheck 
results <- rcmdcheck::rcmdcheck()
results$errors
results$warnings
results$notes

devtools::install()    # Install the package

# for user
devtools::install_github("meglecz/vtamR", ref = "develop") # Install the package from a branch
devtools::install_github("meglecz/vtamR", ref = "v1.0.2") # Install a specific version (tag) 
devtools::install_github("meglecz/vtamR", ref = "1a2b3c4") # Install a specific version (commit) 

usethis::use_readme_rmd()
usethis::use_vignette("vtamR")

devtools::build()
usethis::use_git()
usethis::use_github()

```




