---
title: "vtamR tutorials"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Install and Third Party Programs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  echo=TRUE,
  eval=FALSE,
  fig.width = 6,
  out.width = '100%',
  comment = "#>"
)
```


## [installation](installation.html)

* Installation of vtamR package
* Installation of third party programs
* TaxAsssign data base

## [tutorial-vtamr-pipeline](tutorial-vtamr-pipeline.html)
 
* How to construct a full metabarcoding pipeline
* Supplementary functions
* I/O files and data frames
* Glossary
* Trouble shooting
 
## [from-fastq-to-df](from-fastq-to-df.html)

Quality filtering, merging, trimming demultiplexing, dereplication according to 
different fastq content.

 * One sample per fastq - no tag - no primer
 * One sample per fastq - primer - no tag
 * Several samples per fastq - tags - primers

## [make-mock-composition-file](make-mock-composition-file.html)

How to pick the expected sequences in mock samples from your own data (in case you do not know them in advance).

