---
title: "Benchmark vtamR"
auhor: Emese Meglecz
date: "2025-09-23"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```



# Pool MFZR ZFZR

```{r}
library(vtamR)
library(dplyr)

### set up
cutadapt_path <- "~/miniconda3/envs/vtam/bin/cutadapt"
vsearch_path <- "~/miniconda3/envs/vtam/bin/vsearch"
blast_path <- "~/miniconda3/envs/vtam/bin/blastn"
swarm_path <- "swarm"
num_threads <- 8
sep <- ","
```


## set path to marker (MFZR or ZFZR)
```{r}

dir <- "~/vtamR/local/benchmark/fish"
data_mfzr <- file.path(dir, "results_mfzr", "filter_optimised", "17_PoolReplicates.csv")
data_zfzr <- file.path(dir, "results_zfzr", "filter_optimised", "17_PoolReplicates.csv")
outdir <- file.path(dir, "pool_marker")


sortedinfo <-  file.path(dir, "sorted", "sortedinfo.csv")
input <- file.path(dir, "1_before_filter.csv")
read_count_df <- read.csv(input)
```


```{r}
files <- data.frame(file=c(data_mfzr, data_zfzr),
                    marker=c("MFZR", "ZFZR")
                    )

outfile <- file.path(outdir, "pooled_markers.csv") 
asv_with_centroids <- file.path(outdir, "pooled_datasets_asv_with_centroids.csv") 


###### Pb if same id for mfzr and zfzr!!!!!!!!!!!!!!!!!!
# example 19819

read_count_pool <- PoolDatasets(files, 
                                outfile=outfile, 
                                asv_with_centroids=asv_with_centroids, 
                                mean_over_markers=T,
                                vsearch_path=vsearch_path
                                )

length(unique(read_count_pool$asv_id))
length(unique(read_count_pool$asv))

tmp <- read_count_pool %>%
  select(asv_id, asv) %>%
  distinct() %>%
  group_by(asv_id) %>%
  summarize(nb = length(asv))
```


# Taxassign
```{r}
taxonomy  <- "/home/meglecz/mkCOInr/COInr/COInr_for_vtam_2025_05_23_dbV5/COInr_for_vtam_taxonomy.tsv"
blast_db <- "/home/meglecz/mkCOInr/COInr/COInr_for_vtam_2025_05_23_dbV5/COInr_for_vtam"
blast_path <- "~/miniconda3/envs/vtam/bin/blastn"

outfile <- file.path(outdir, "TaxAssign.csv")
asv_tax <- TaxAssign(asv=read_count_pool, 
                     taxonomy=taxonomy, 
                     blast_db=blast_db, 
                     blast_path=blast_path, 
                     outfile=outfile, 
                     num_threads=num_threads
                     )

sortedinfo <- file.path(dir, "results_mfzr", "sorted", "sortedinfo.csv") #  Can be any of the 2 sortedinfo, since alnly sample liste and tymes are interesting

#####!!!!! OK, since mfzr is longer, abd amplifies avarything, but not OK in more comlex situations
mock <- read.csv("/home/meglecz/vtamR/local/benchmark/fish/data/mock_composition_mfzr.csv")
outfile=file.path(outdir, "Asvtable_with_TaxAssign_pooled_markers.csv")
asv_table_df <- WriteASVtable(read_count_pool, 
                              outfile=outfile, 
                              asv_tax=asv_tax, 
                              sortedinfo=sortedinfo, 
                              add_empty_samples=T, 
                              add_sums_by_sample=T, 
                              add_sums_by_asv=T, 
                              add_expected_asv=T,
                              mock_composition=mock
                              )
```


