---
title: "Benchmark vtamR"
auhor: Emese Meglecz
date: "2025-09-23"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```



# Get fish DATA

Download manually fish data to ~/vtamR/local/benchmark/fish/download
https://datadryad.org/dataset/doi:10.5061/dryad.f40v5

Create folder for fish data and move downloaded file into it
```{bash, include=FALSE}
cd  ~/vtamR/local/benchmark/fish/download
```

unzip data
```{bash, include=FALSE}
unzip doi_10_5061_dryad_f40v5__v20170802.zip 
```

move essential files to  /home/meglecz/vtamR/local/Benchmark/fish/data
```{bash, include=FALSE}
cd ..
mkdir data
mv download/MFZR* data
mv download/ZFZR* data

cp download/README_for_MFZR1_S4_L001_R1_001.fastq.tar.csv data/MFZR.csv
cp download/README_for_ZFZR1_S1_L001_R1_001.fastq.tar.csv data/ZFZR.csv
```


untar
```{bash, include=FALSE}
cd data
tar -zxvf MFZR1_S4_L001_R1_001.fastq.tar.gz
tar -zxvf MFZR1_S4_L001_R2_001.fastq.tar.gz
tar -zxvf MFZR2_S5_L001_R1_001.fastq.tar.gz
tar -zxvf MFZR2_S5_L001_R2_001.fastq.tar.gz
tar -zxvf MFZR3_S6_L001_R1_001.fastq.tar.gz
tar -zxvf MFZR3_S6_L001_R2_001.fastq.tar.gz
tar -zxvf MFZR1_S1_L001_R1_001.fastq.tar.gz
tar -zxvf ZFZR1_S1_L001_R2_001.fastq.tar.gz
tar -zxvf ZFZR2_S2_L001_R1_001.fastq.tar.gz
tar -zxvf ZFZR2_S2_L001_R2_001.fastq.tar.gz
tar -zxvf ZFZR3_S3_L001_R1_001.fastq.tar.gz
tar -zxvf ZFZR3_S3_L001_R2_001.fastq.tar.gz

rm *.gz
```

zip
```{bash, include=FALSE}
gzip *.fastq
```


## Make fastqinfo file

```{r, include=FALSE}
library(dplyr)
```

## Make fastqinfo MFZR
```{r, include=FALSE}
dir <- "~/vtamR/local/benchmark/fish"
fastqinfo <- read.csv(file.path(dir, "data", "MFZR.csv"))
colnames(fastqinfo) <- c("replicate","tag_fw","primer_fw","tag_rv","primer_rv","marker","sample")

fastqinfo <- fastqinfo %>%
  mutate(replicate = 1, fastq_fw = "MFZR1_S4_L001_R1_001.fastq.gz", fastq_rv = "MFZR1_S4_L001_R2_001.fastq.gz") %>%
  mutate(
    sample_type = case_when(
      grepl("^Tpos", sample) ~ "mock",
      grepl("^Tneg", sample) ~ "negative",
      TRUE ~ "real"
      ) 
    )%>%
  mutate(
    habitat = case_when(
      grepl("^Tpos", sample) ~ "freshwater",
      grepl("^[0-9]", sample) ~ "freshwater",
      grepl("^Tneg", sample) ~ NA,
      TRUE ~ "brackish"
    )
  ) %>%
  select(tag_fw, primer_fw, tag_rv, primer_rv, sample, sample_type, habitat, replicate, fastq_fw, fastq_rv)

fastqinfo2 <- fastqinfo %>%
  mutate(replicate = 2, fastq_fw = "MFZR2_S5_L001_R1_001.fastq.gz", fastq_rv = "MFZR2_S5_L001_R2_001.fastq.gz")

fastqinfo3 <- fastqinfo %>%
  mutate(replicate = 3, fastq_fw = "MFZR3_S6_L001_R1_001.fastq.gz", fastq_rv = "MFZR3_S6_L001_R2_001.fastq.gz")

fastqinfo_mfzr <- rbind(fastqinfo, fastqinfo2, fastqinfo3)
write.csv(fastqinfo_mfzr, file.path(dir, "data", "fastqinfo_mfzr.csv"), row.names = FALSE)
rm(fastqinfo, fastqinfo2, fastqinfo3)

```


## Make fastqinfo ZFZR
```{r, include=FALSE}
fastqinfo <- read.csv(file.path(dir, "data", "ZFZR.csv"))
colnames(fastqinfo) <- c("replicate","tag_fw","primer_fw","tag_rv","primer_rv","marker","sample")

fastqinfo <- fastqinfo %>%
  mutate(replicate = 1, fastq_fw = "ZFZR1_S1_L001_R1_001.fastq.gz", fastq_rv = "ZFZR1_S1_L001_R2_001.fastq.gz") %>%
  mutate(
    sample_type = case_when(
      grepl("^Tpos", sample) ~ "mock",
      grepl("^Tneg", sample) ~ "negative",
      TRUE ~ "real"
      ) 
    )%>%
  mutate(
    habitat = case_when(
      grepl("^Tpos", sample) ~ "freshwater",
      grepl("^[0-9]", sample) ~ "freshwater",
      grepl("^Tneg", sample) ~ NA,
      TRUE ~ "brackish"
    )
  ) %>%
  select(tag_fw, primer_fw, tag_rv, primer_rv, sample, sample_type, habitat, replicate, fastq_fw, fastq_rv)

fastqinfo2 <- fastqinfo %>%
  mutate(replicate = 2, fastq_fw = "ZFZR2_S2_L001_R1_001.fastq.gz", fastq_rv = "ZFZR2_S2_L001_R2_001.fastq.gz")

fastqinfo3 <- fastqinfo %>%
  mutate(replicate = 3, fastq_fw = "ZFZR3_S3_L001_R1_001.fastq.gz", fastq_rv = "ZFZR3_S3_L001_R2_001.fastq.gz")

fastqinfo_zfzr <- rbind(fastqinfo, fastqinfo2, fastqinfo3)
write.csv(fastqinfo_mfzr, file.path(dir, "data", "fastqinfo_zfzr.csv"), row.names = FALSE)
rm(fastqinfo, fastqinfo2, fastqinfo3)

```



## From fastq to read_count_df

```{r, include=FALSE}
library(vtamR)
library(dplyr)

## set up
cutadapt_path <- "~/miniconda3/envs/vtam/bin/cutadapt"
vsearch_path <- "~/miniconda3/envs/vtam/bin/vsearch"
num_threads <- 8
sep <- ","

dir <- "~/vtamR/local/benchmark/fish"
fastq_dir <- file.path(dir, "data")
```


### Run one for MFZR and once for ZFZR
```{r}
### MFZR
outdir <- file.path(dir, "results_mfzr")
fastqinfo <- fastqinfo_mfzr
### ZFZR
outdir <- file.path(dir, "results_zfzr")
fastqinfo <- fastqinfo_zfzr

### Merge
merged_dir <- file.path(outdir, "merged")
fastainfo_df <- Merge(fastqinfo, 
                      fastq_dir=fastq_dir, 
                      vsearch_path=vsearch_path, 
                      outdir=merged_dir,
                      fastq_maxee=1,
                      fastq_maxns=0,
                      fastq_allowmergestagger=F,
                      num_threads=num_threads
                      
)

### demultiplex
sorted_dir <- file.path(outdir, "sorted")
sortedinfo_df <- SortReads(fastainfo_df, 
                           fasta_dir=merged_dir, 
                           outdir=sorted_dir, 
                           check_reverse=TRUE, 
                           cutadapt_path=cutadapt_path, 
                           vsearch_path=vsearch_path,
                           num_threads=num_threads
)


updated_asv_list <- file.path(outdir, "asv_list.csv")
outfile <- file.path(outdir, "1_before_filter.csv")
read_count_df <- Dereplicate(sortedinfo_df, 
                             dir=sorted_dir, 
                             updated_asv_list = updated_asv_list,
                             outfile=outfile
)
```


