---
title: "vtamR Developer notes"
auhor: Emese Meglecz
date: "2024-06-24"
output:
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```


```{r}
### Developer
# Creating a package
install.packages(c("devtools", "roxygen2", "usethis", "testthat"))
usethis::create_package("path/to/your/packageName")
usethis::use_git()
usethis::use_github()

#### Write the package

# Replaces roxygenise() and usethis::use_roxygen_md()
# It is for me to run, not necessary for users who used install(vtamR)
devtools::document() # generate doc

# create a template for README.Rmd que le develper Edit. It is in .builtignore
usethis::use_readme_rmd()
# make a README.Rmd from README.Rmd. This should not be edited manually
# When building the readme, the Rmd and its chunks are executed, so all example codes should work. If not, make eval=FALSE
devtools::build_readme()

# creates vignette and adds modif to DESCRIPTION
usethis::use_vignette("vtamR")
# Adapt tutorial_vtamR.Rmd to vignette
# To Build, Code must execute or use eval=FALSE; 
# Build execute vtam.Rmd to R and html to doc dir
# and creates a copy of vtamR.Rmd to doc as well.
# It the vignette needs to be edited, the file in 
# vignettes/ should be edited and built again.
devtools::build_vignettes()

 # Run checks before releasing a package
devtools::check()     
## OR rcmdcheck 
results <- rcmdcheck::rcmdcheck()
results$errors
results$warnings
results$notes

# Load package without installing; Use during development
devtools::load_all()   

### to test as a package 
# Install the package with vignettes, but vignettes are not available for users it is only local
devtools::install(build_vignettes = TRUE)
# make a tarball with the package with vignettes, It includes vignettes for the users
devtools::build(vignettes = TRUE)
# creates  "/home/meglecz/vtamR_0.2.0.tar.gz", than add the tarball to github (pre-)release

#### users
# simple. intsallas automatically from github and handles dependencies
# BUT this will not make vignettes
pak::pak("meglecz/vtamR@develop")

## To get vignettes for the users, WO cloning and installing use a tarball
# Handles only dependencies from CRAN
install.packages("https://github.com/meglecz/vtamR/releases/download/v0.2.0-test1/vtamR_0.2.0.tar.gz",
                 repos = NULL,
                 type = "source")
# Handles other dependencies and suggested packages
pak::pkg_install("https://github.com/meglecz/vtamR/releases/download/v0.2.0-test1/vtamR_0.2.0.tar.gz")




   
# USER
library("vtamR") 
# this replaces devtools::load_all() , 
# no need to create doc separately with devtools::document() or roxigenize

##see vignettes
vignette(package = "vtamR")
vignette("tutorial-vtamr-pipeline") 
vignette("installation") 
vignette("make-mock-composition-file") 









############
# create a rda with the asv_tax, so users can load it
full_asv_tax <- asv_tax
usethis::use_data(full_asv_tax, overwrite = TRUE)
rm(full_asv_tax)
data(full_asv_tax)
############

```




